### ISSUE TITLE
LTR TEXT

### ISSUE THREAD

**Issue by kem0x** [leomontenegro6/aade#5]
We are translating the game to Arabic (extraordinary team @wumdh.com)
so we was asking about how to reverse the text appearance to be left to right as the Arabic language should be because of the lack of asm experience

**Comment by leomontenegro6** [comment]
Hi kareem, sorry for replying your question just now.

Anyway, AADE isn't a tool for editing Ace Attorney texts by itself. Instead, it depends on tools of other developers, such as[ onepiecefreak's dlgtool](https://github.com/onepiecefreak3/dlgTool). So, even if we implement something such as LTR support on AADE, it won't work properly if other tools aren't changed in order to add support for that feature. So I recommend you to ask that question for the developers of the other tools, such as the one I mentioned above.

I'm closing that issue for now, but if you get some progress talking to the developers of the other tools, I can reopen it later.
